"""
Pydantic models for Patient Summary service responses.
"""

from datetime import datetime, timezone
from typing import Optional
from uuid import UUID

from pydantic import BaseModel, Field

from shared.event_models import PatientTimeline


class PatientRecommendation(BaseModel):
    """
    A single recommendation for patient care or coverage.

    Generated by agentic analysis of patient timeline data.
    Stored with content hash for deduplication.

    - When creating: provide canonical_patient_id, summary, risk_tier
    - When reading from DB: all fields are populated
    """

    canonical_patient_id: UUID = Field(description="Patient UUID")
    summary: str = Field(description="Recommendation text (e.g., coverage decision, next steps)")
    risk_tier: Optional[str] = Field(None, description="Risk level: high, medium, low")
    id: Optional[int] = Field(None, description="Primary key (DB-generated)")
    content_hash: Optional[str] = Field(None, description="SHA256 hash of summary for deduplication (DB-generated)")
    generated_at: Optional[datetime] = Field(None, description="When this recommendation was generated (DB-generated)")


class PatientSummary(BaseModel):
    """
    Aggregated patient summary combining timeline and recommendations.

    Provides a single view of:
    - Current patient state (from PatientTimeline materialized view)
    - Care recommendations and coverage decisions
    - Risk assessment and next steps
    """

    # Patient identity & timeline
    canonical_patient_id: UUID = Field(description="Patient UUID")
    timeline: Optional[PatientTimeline] = Field(None, description="Latest timeline event for this patient")

    # Recommendations (paginated)
    recommendations: list[PatientRecommendation] = Field(
        default_factory=list,
        description="List of recommendations for this patient",
    )
    recommendation_count: int = Field(0, description="Total number of recommendations")
    page: int = Field(1, description="Current page (1-indexed)")
    page_size: int = Field(100, description="Recommendations per page")

    # Summary metadata
    last_updated: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="When this summary was last generated",
    )
    high_risk_count: int = Field(0, description="Number of high-risk recommendations")
    medium_risk_count: int = Field(0, description="Number of medium-risk recommendations")
    low_risk_count: int = Field(0, description="Number of low-risk recommendations")

    @property
    def highest_risk_tier(self) -> Optional[str]:
        """Return the highest risk tier present in recommendations."""
        if self.high_risk_count > 0:
            return "high"
        if self.medium_risk_count > 0:
            return "medium"
        if self.low_risk_count > 0:
            return "low"
        return None

    @property
    def primary_recommendation(self) -> Optional[PatientRecommendation]:
        """Return the most recent recommendation (first in list)."""
        return self.recommendations[0] if self.recommendations else None


class PatientSummaryResponse(BaseModel):
    """
    HTTP response wrapper for patient summary.

    Includes status and metadata for API clients.
    """

    success: bool = Field(description="Whether the request succeeded")
    data: Optional[PatientSummary] = Field(None, description="Patient summary data")
    error: Optional[str] = Field(None, description="Error message if unsuccessful")
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc), description="Response timestamp")
