global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'patient-api'
    static_configs:
      - targets: ['patient-api:8000']
    metrics_path: '/metrics'

  - job_name: 'ingestion-gateway'
    static_configs:
      - targets: ['ingestion-gateway:8010']
    metrics_path: '/metrics'

  - job_name: 'patient-data'
    static_configs:
      - targets: ['patient-data:8020']
    metrics_path: '/metrics'

  - job_name: 'patient-event-reconciliation'
    static_configs:
      - targets: ['patient-event-reconciliation:8030']
    metrics_path: '/metrics'

  - job_name: 'patient-timeline'
    static_configs:
      - targets: ['patient-timeline:8040']
    metrics_path: '/metrics'

  - job_name: 'patient-summary'
    static_configs:
      - targets: ['patient-summary:8050']
    metrics_path: '/metrics'

  - job_name: 'notification'
    static_configs:
      - targets: ['notification:8060']
    metrics_path: '/metrics'

  - job_name: 'patient-reconciliation-worker'
    static_configs:
      - targets: ['patient-reconciliation-worker:8070']
    metrics_path: '/metrics'

  - job_name: 'npi-registry'
    static_configs:
      - targets: ['npi-registry:8080']
    metrics_path: '/metrics'
